name: Workflow Demo

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Create a text file
      run: echo "Hello, world!" > hello.txt

    - name: Archive text file
      uses: actions/upload-artifact@v3
      with:
        name: hello-artifact
        path: hello.txt
  
  download:
    runs-on: ubuntu-latest
    needs: [build]
    permissions:
      contents: write
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Download file
      uses: actions/download-artifact@v3
      with:
        name: hello-artifact
        path: ./artifacts

    - name: Display content
      run: cat ./artifacts/hello.txt

    - name: Commit new file
      run: |
        git config --local user.name "GitHub Actions"
        git config --local user.email "actions@github.com"
        git add ./artifacts/hello.txt
        git commit -m "Add hello.txt"
        git push